name: Code Coverage

on:
  push:
    branches: [ "ci/test-coverage" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: nightly
            components: llvm-tools-preview
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.8
      - name: Install cargo-llvm-cov
        run: if [[ ! -e ~/.cargo/bin/cargo-llvm-cov ]]; then cargo install cargo-llvm-cov; fi
      - name: Test and report coverage
        run: cargo +nightly llvm-cov -q --doctests --branch --all --ignore-filename-regex "(example-crates/*|crates/testenv/*)" --all-features
